/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package demo;

import java.io.IOException;
import java.util.List;
import java.util.Random;
import java.io.File;

import org.openqa.selenium.By;
import org.openqa.selenium.OutputType;
import org.openqa.selenium.TakesScreenshot;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebDriverException;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.edge.EdgeDriver;
import org.openqa.selenium.io.FileHandler;
import org.openqa.selenium.support.ui.Select;

public class App {

    public static void main(String[] args) throws Exception {
        
        // DRIVER PATH
        System.setProperty("webdriver.edge.driver", "C://Users//janfo//Desktop//msedgedriver.exe");

        // START EDGE SESSION
        WebDriver driver = new EdgeDriver();
        driver.manage().window().maximize();
        driver.manage().deleteAllCookies();

        driver.get("https://vodafone.cz/");

        driver.get("https://vodafone.cz/telefony");

        // FILLING FORM
        Select customerType = new Select(driver.findElement(By.id("customerTypeSelect")));
        customerType.selectByVisibleText("Nejsem");

        WebElement customerTarif = driver.findElement(By.className("fakeSelect"));
        customerTarif.click();
        List<WebElement> options = customerTarif.findElements(By.className("tariffItem__name"));
        options.get(5).click(); // selection "Ne, chci telefon bez tarifu"
        System.out.println("Selected Option: Ne, chci telefon bez tarifu");

        // NOT GOOD PRACTICE
        Thread.sleep(5000);

        // MOBILE SELECTION
        WebElement temp = driver.findElement(By.xpath("//img[@src='/public/galleries/23/22205/_thbs_/256X240__samsung_galaxy_z_flip3_5g_phantom_black_celo_a.png']"));
        temp.click();

        // MOBILE PURSCHASE
        driver.findElement(By.linkText("Koupit telefon bez tarifu")).click();
        
        // MAKE SCREENSHOT
        TakesScreenshot ts=(TakesScreenshot)driver;
        try {
            Random rand = new Random();

            // nextInt as provided by Random is exclusive of the top value so you need to add 1 
            
            int randomTimeStamp = rand.nextInt((999 - 10) + 1) + 10;
            FileHandler.copy(ts.getScreenshotAs(OutputType.FILE), new File("C:/Users/janfo/Desktop/Selenium/Screenshot" + randomTimeStamp + ".png"));
        } catch (WebDriverException e) {
     
        } catch (IOException e) {
     
        }

        // CHECKBOX CONDITIONS
        driver.findElement(By.cssSelector("label[for='unfinishedOrderHelp']")).click(); 

        // BROWSER QUIT
        //driver.quit();
    }
}
